import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { plan } from '@/lib/plan';
import { getPlanForLanguage } from '@/lib/multi-language-plans';
export type AudioEntry={id:string;name:string;url:string;createdAt:string;source:'recorded'|'uploaded';size:number};
export type DayProgress={completed:boolean;confidence:number;notes:string;transcript:string;aiFeedback:string;vocabulary:string;audioEntries:AudioEntry[]};
export type TrackerState={selectedDay:number;selectedLanguage:string;days:Record<number,DayProgress>};
const empty=():DayProgress=>({completed:false,confidence:0,notes:'',transcript:'',aiFeedback:'',vocabulary:'',audioEntries:[]});
const createInitialState=(languageCode='en'):TrackerState=>{const languagePlan=getPlanForLanguage(languageCode);return{selectedDay:1,selectedLanguage:languageCode,days:Object.fromEntries(languagePlan.map(d=>[d.id,empty()]))}};
const initialState:TrackerState=createInitialState('en');
const slice=createSlice({name:'tracker',initialState,reducers:{setSelectedDay(s,a:PayloadAction<number>){s.selectedDay=a.payload},setSelectedLanguage(s,a:PayloadAction<string>){const newPlan=getPlanForLanguage(a.payload);s.selectedLanguage=a.payload;s.selectedDay=1;s.days=Object.fromEntries(newPlan.map(d=>[d.id,empty()]))},toggleCompleted(s,a:PayloadAction<number>){s.days[a.payload].completed=!s.days[a.payload].completed},setConfidence(s,a:PayloadAction<{dayId:number;value:number}>){s.days[a.payload.dayId].confidence=a.payload.value},setField(s,a:PayloadAction<{dayId:number;field:'notes'|'transcript'|'aiFeedback'|'vocabulary';value:string}>){s.days[a.payload.dayId][a.payload.field]=a.payload.value},addAudioEntry(s,a:PayloadAction<{dayId:number;entry:AudioEntry}>){s.days[a.payload.dayId].audioEntries.unshift(a.payload.entry)},removeAudioEntry(s,a:PayloadAction<{dayId:number;entryId:string}>){s.days[a.payload.dayId].audioEntries=s.days[a.payload.dayId].audioEntries.filter(x=>x.id!==a.payload.entryId)},hydrateState(_,a:PayloadAction<TrackerState>){return a.payload},resetAll(s){const newState=createInitialState(s.selectedLanguage);return newState}}});
export const {setSelectedDay,setSelectedLanguage,toggleCompleted,setConfidence,setField,addAudioEntry,removeAudioEntry,hydrateState,resetAll}=slice.actions;
export default slice.reducer;
