export type DayPlan={id:number;title:string;goal:string;readingScript:string;tasks:string[]};
export const plan:DayPlan[]=[
{id:1,title:'Break the Fear',goal:'Speak about yourself without worrying about mistakes.',readingScript:'Hello. My name is __________. I am from Bangladesh. Bengali is my first language, and I am learning English to become more confident. I want to speak clearly at work and in daily life. I may make mistakes, but I will keep going.',tasks:['Read the script aloud 3 times','Record a 1 to 2 minute introduction','Rate your confidence from 1 to 5','Mark the day complete']},
{id:2,title:'Talk About Your Day',goal:'Describe your daily routine in simple English.',readingScript:'I usually wake up in the morning and start my day with simple tasks. After that, I get ready for work. During the day, I complete my tasks, talk to people, and try to stay focused. In the evening, I spend time with my family and take some rest.',tasks:['Read the script aloud 3 times','Speak for 2 minutes about your routine','Upload or record audio','Write one sentence about what felt difficult']},
{id:3,title:'Pronunciation Day',goal:'Say words slowly and clearly.',readingScript:'Today I will focus on pronunciation. I will speak slowly, clearly, and with confidence. I do not need a perfect accent. I only need to be understandable. Clear communication is more important than sounding perfect.',tasks:['Read the script slowly 5 times','Record key words and short lines','Listen to your own audio once','Write down 3 words you want to improve']},
{id:4,title:'Work English',goal:'Speak about your job and skills.',readingScript:'I work in a professional environment, and I want to speak about my work in English. I can describe my role, my responsibilities, and my skills. The more I practice, the more natural my professional English will become.',tasks:['Read the script aloud 3 times','Record a 2-minute summary of your work','Add one new work-related phrase','Complete the checklist']},
{id:5,title:'Useful Phrases',goal:'Use natural short phrases in speech.',readingScript:'Let me think about that. That is a good question. In my opinion, practice is the key to improvement. From my experience, speaking every day helps a lot. These small phrases make my English sound more natural.',tasks:['Read the script 4 times','Record the script once','Use 3 phrases in your own sentences','Write which phrase you liked most']},
{id:6,title:'Describe an Object',goal:'Build confidence by describing simple things.',readingScript:'This is an object I use every day. It is useful, practical, and important to my routine. I can describe its color, shape, size, and purpose. This kind of practice is small, but it improves fluency over time.',tasks:['Read the script aloud','Describe your phone, laptop, or table for 2 minutes','Record or upload audio','Give yourself a fluency score']},
{id:7,title:'Tell a Story',goal:'Speak in sequence using simple storytelling.',readingScript:'One memorable day in my life taught me something important. At first, I felt nervous and uncertain. Then something happened that changed the situation. Even a small event can become a meaningful story when we explain it clearly and honestly.',tasks:['Read the script 3 times','Tell a real story for 2 to 3 minutes','Try using first, then, after that, finally','Complete the checklist']},
{id:8,title:'Think in English',goal:'Reduce Bangla-to-English delay.',readingScript:'Now I am practicing English in real time. I am sitting here, breathing calmly, and choosing simple words. I do not need difficult vocabulary. I only need clear thoughts and short sentences.',tasks:['Read the script 3 times','Speak for 2 minutes about what you are doing right now','Avoid translating every sentence from Bangla','Write one moment when English came naturally']},
{id:9,title:'Question and Answer',goal:'Answer common questions smoothly.',readingScript:'Why am I learning English? I am learning English to grow personally and professionally. What is difficult for me? Sometimes I hesitate, and sometimes I search for words. Daily practice and listening carefully will help me improve.',tasks:['Read the script aloud','Answer 3 personal questions in English','Record your answers','Write one better answer after listening']},
{id:10,title:'Mirror Practice',goal:'Build presence and body-language confidence.',readingScript:'Today I will practice in front of a mirror. I will stand straight, look at myself, and speak with calm energy. Confidence is not only in words. It is also in my expression, rhythm, and eye contact.',tasks:['Read the script in front of a mirror','Speak about your strengths for 2 minutes','Record if possible','Rate your confidence again']},
{id:11,title:'Linking Words',goal:'Connect ideas more naturally.',readingScript:'I want my English to flow better. Because of that, I am learning linking words. For example, I can say because, however, actually, basically, and therefore. These words help me connect my thoughts.',tasks:['Read the script 3 times','Make 5 sentences using linking words','Say them aloud','Record one short paragraph']},
{id:12,title:'News Summary',goal:'Explain what you read in simple English.',readingScript:'Today I read a piece of news and tried to understand the main point. I do not need difficult vocabulary. I only need to say what happened, where it happened, and why it matters.',tasks:['Read the script aloud','Read one short article','Summarize it in 1 to 2 minutes','Write 3 new words from the article']},
{id:13,title:'No-Stopping Practice',goal:'Speak continuously even with mistakes.',readingScript:'Today my target is flow, not perfection. I will keep speaking without stopping every few seconds. If I forget a word, I will use another simple word. Fluency grows when I keep moving.',tasks:['Read the script with energy','Speak for 3 minutes without stopping','Record the session','Note how many times you paused']},
{id:14,title:'Interview Introduction',goal:'Present yourself professionally.',readingScript:'Hello, my name is __________. I am a professional from Bangladesh, and I am improving my spoken English for work and growth. I want to sound calm, clear, and confident. A strong introduction creates a strong first impression.',tasks:['Read the script aloud','Record your interview-style introduction','Improve it once after listening','Mark the day done']},
{id:15,title:'Final Reflection',goal:'Measure progress and celebrate improvement.',readingScript:'This is day fifteen of my English practice journey. I started with hesitation, but I continued step by step. Now I can hear changes in my voice, my confidence, and my fluency. I am proud of my progress, and I will continue after today.',tasks:['Read the script proudly','Record a final 3 to 5 minute reflection','Compare it with day 1','Write what improved most']}
];
